### ISSUE TITLE
composer 安装有问题, 考虑参加FrameworkBenchmarks吗?

### ISSUE THREAD

**Issue by cexll** [passwalls/mark#1]
composer required mark/mark 有问题
直接git clone 
作者考虑参加FrameworkBenchmarks吗,这是一个比较全面的测试
https://github.com/TechEmpower/FrameworkBenchmarks
案例可以找到workerman 的案例操作 和webman

**Comment by passwalls** [comment]
是`composer required mark-php/mark` 已经修正。

我先研究下FrameworkBenchmarks，不一定参加。

**Comment by cexll** [comment]
恩
