### ISSUE TITLE
"Caching" does not work for same URL with different methods

### ISSUE THREAD

**Issue by MJSidor** [passwalls/mark#10]
https://github.com/passwalls/mark/blob/1f0ed9327809976e8e012d51d5fa72b309910681/src/App.php#L159
https://github.com/passwalls/mark/blob/1f0ed9327809976e8e012d51d5fa72b309910681/src/App.php#L165
https://github.com/passwalls/mark/blob/1f0ed9327809976e8e012d51d5fa72b309910681/src/App.php#L174

**Comment by MJSidor** [comment]
in REST APIs this "caching" tactic causes bugs for endpoints with multiple methods available (ex. GET /user & POST /user). Wrong callbacks are being used for requests, if the endpoint has been requested before with a different method. Simply containing the method in the $callbacks array would fix the issue. Cheers!

**Comment by passwalls** [comment]
You are right. Fixed and thank you for your post. 👍
