### ISSUE TITLE
Sorry for this

### ISSUE THREAD

**Issue by juan-morales** [passwalls/mark#17]
Sorry for this but this is NOT a framework at all. 
Is just a wrapper around workerman for 6 methods. 

I was expecting more honestly. 

Dont want to hurt anyones feelings with this either.

**Comment by passwalls** [comment]
Hi juan-morales.
I'm so sorry if this project causes discomfort to you. It was very unexpected.

Perhaps everyone has a different definition of the framework.
Yes, mark combines `nikic/fast-route` with `workerman/workerman`, and only provides six methods, it can be regarded as a **micro** API framework for me.

However It doesn't matter what we call it. The most important thing is that it is useful to many people. Imagine Mark provides a minimum core, which makes it easier for us to expand more functions based on actual needs, which is a happy thing.
Have a good day 🤝.
