### ISSUE TITLE
Bind to hostname

### ISSUE THREAD

**Issue by dotsensei** [passwalls/mark#5]
Hi,
I'm trying to bind the app to hostname, so I can have two instances of the app on the same IP and same port, but on different hostnames.
Service starts ok, but when I visit the domain I get Connection Refused by browser. Binding to IP works fine. How can I debug, or is it possible at all?
Thanks

**Comment by passwalls** [comment]
> I'm trying to bind the app to hostname, so I can have two instances of the app on the same IP and same port, but on different hostnames.

Hi dotsensei.
I can not understand what's that mean. 
Do you want to achieve the following effect？
<hr>

```php
$api_a = new App('http://doamin_a.com:3000');
$api_a->any('/', function ($requst) {
    return 'Hello I'm api A';
});

$api_b = new App('http://doamin_b.com:3000');
$api_b->any('/', function ($requst) {
    return 'Hello I'm api B';
});
```

When visit `http://doamin_a.com:3000`shows `Hello I'm api A`.
When visit `http://doamin_b.com:3000`shows `Hello I'm api B`.
<hr>

You can describe in detail what you want to achieve. Better show the code.

**Comment by dotsensei** [comment]
I have two subdomains, **x.example.com** and **y.example.com**, resolving to the same IP address. (IPv4 and IPv6). Both of them should be accessible on port 80. Using the following code:

`$api_a = new App('http://x.example.com:80');
$api_a->count = 4; // process count
$api_a->any('/', function ($requst) {
    return 'Hello Im api A';
});

$api_b = new App('http://y.example.com:80');
$api_b->count = 4; // process count
$api_b->any('/', function ($requst) {
    return 'Hello Im api B';
});

$api_a->start();
$api_b->start();`

But when I start the app, going to those domains results in ERR_CONNECTION_REFUSED

If I change the port, it is the same result.

It only works if I launch an API with IP address instead of a domain.

**Comment by dotsensei** [comment]
With curl managed to send request to the two domains and got some debug info (the same):

`Error: Call to a member function dispatch() on null in /var/www/html/vendor/mark-php/mark/src/App.php:92
Stack trace:
#0 /var/www/html/vendor/workerman/workerman/Connection/TcpConnection.php(660): Mark\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(Workerman\Protocols\Http\Request))
#1 /var/www/html/vendor/workerman/workerman/Events/Select.php(293): Workerman\Connection\TcpConnection->baseRead(Resource id #34)
#2 /var/www/html/vendor/workerman/workerman/Worker.php(2430): Workerman\Events\Select->loop()
#3 /var/www/html/vendor/workerman/workerman/Worker.php(1555): Workerman\Worker->run()
#4 /var/www/html/vendor/workerman/workerman/Worker.php(1385): Workerman\Worker::forkOneWorkerForLinux(Object(Mark\App))
#5 /var/www/html/vendor/workerman/workerman/Worker.php(1359): Workerman\Worker::forkWorkersForLinux()
#6 /var/www/html/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#7 /var/www/html/vendor/mark-php/mark/src/App.php(74): Workerman\Worker::runAll()
#8 /var/www/html/test.php(18): Mark\App->start()
#9 {main}`

**Comment by passwalls** [comment]
Mark does not support binding domain names. And it does not support creating multiple app instances in one startup file.

The simplest way is to create two startup files start_a.php start_b.php.
start_a.php
```
$api_a = new App('http://0.0.0.0:3000');
```
Run command `php start_a.php start -d`

start_b.php
```
$api_b = new App('http://0.0.0.0:3001');
```
Run command `php start_b.php start -d`

Then use nginx proxy to proxy requests from different domain names to different app instances.

Nginx config.
example_a.conf
```
server {
  listen 80;
  server_name  example_a.com;
  location /
  {
    proxy_pass http://127.0.0.1:3000;
  }
}
```

example_b.conf
```
server {
  listen 80;
  server_name  example_b.com;
  location /
  {
    proxy_pass http://127.0.0.1:3001;
  }
}
```
