### ISSUE TITLE
There is only GET and POST methods available?

### ISSUE THREAD

**Issue by cierzniak** [passwalls/mark#8]
I've seen just get and post methods, how about put/patch/delete?
```php
public function get($path, $callback);
public function post($path, $callback);
public function any($path, $callback);
```

From [nikic/FastRoute](https://github.com/nikic/FastRoute#shortcut-methods-for-common-request-methods) docs:

> For the GET, POST, PUT, PATCH, DELETE and HEAD request methods shortcut methods are available.

Is it just a missing implementation in marks base methods?

**Comment by passwalls** [comment]
Mark support PUT, PATCH, DELETE OPTIONS  HEAD methods now (since version 1.1.8).

**Comment by cierzniak** [comment]
Great, thanks!
